spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:/db/changelog/changelog.xml
spring.liquibase.default-schema=public

#spring.liquibase.enabled=true

jwt.token.secret=${SECRET}
jwt.token.expireTime=${EXPIRE_TIME}

example.logger.enabled=true