spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:/db/changelog/changelog.xml
spring.liquibase.default-schema=public

jwt.token.secret=secret
jwt.token.expireTime=600000

spring.kafka.producer.bootstrap-servers=kafka:9092
spring.kafka.topic.welcomeMailTopic=welcomeMailTopic
spring.kafka.topic.customTopic=customTopic

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.value.default.type=example.spring.kafka.event.NotificationEvent

example.logger.enabled=true