jdbc.url = jdbc:postgresql://localhost:5432/postgres
jdbc.driverClassName = org.postgresql.Driver
jdbc.username = postgres
jdbc.password = postgres
hibernate.dialect = org.hibernate.dialect.PostgresSQL10Dialect
hibernate.default_schema = management
hibernate.hbm2ddl.auto = update
hibernate.show_sql = true
hibernate.format_sql = true
#hibernate.allow_update_outside_transaction = true