version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - project_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  project-management-api:
    build: .
    container_name: project-management-api
    environment:
#      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
      DATABASE_URL: jdbc:postgresql://host.docker.internal:5432/postgres
      USERNAME: postgres
      PASSWORD: postgres
      SECRET: secret
      EXPIRE_TIME: 600000
    ports:
      - 8080:8080
    depends_on:
      - postgres
#      - kafka-ui

  mail-api:
    build: ../mail
    container_name: mail-api
    ports:
      - 8081:8081
    depends_on:
      - project-management-api

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
#
#    ports:
#      - 2181:2181
#
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9094:9094
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - 8082:8082
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
#    depends_on:
#      - kafka


#  sonarqube:
#    image: sonarqube:community
#    volumes:
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_extensions:/opt/sonarqube/extensions
#      - sonarqube_logs:/opt/sonarqube/logs
#    ports:
#      - "9000:9000"
volumes:
  project_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: