spring.application.name=mail

spring.kafka.consumer.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=testGroupId

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=myowndn@gmail.com
spring.mail.password=tyjx imxr rvuj viwm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true