-- create schema testSchema;
-- create table testSchema.testTable(first_name varchar,
--                         last_name varchar,
--                         age int,
--                         skill varchar);