package example.spring.config;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Contact;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.info.License;
import io.swagger.v3.oas.annotations.servers.Server;

@OpenAPIDefinition(
        info = @Info(
                contact = @Contact(
                        name = "test",
                        email = "test",
                        url = "htts://google.com"
                ),
                description = "OpenApi documentation for Project Management Application",
                title = "AutoGeneratedDocs, v1",
                version = "1.0",
                license = @License(
                        name = "Licence name",
                        url = "license-url.com"
                ),
                termsOfService = "Terms of Service"
        ),
        servers = {
                @Server(
                        description = "DEV",
                        url = "localhost:8080"
                ),
                @Server(
                        description = "TEST",
                        url = "localhost:8080"
                ),
                @Server(
                        description = "UAT",
                        url = "localhost:8080"
                )
        }
)
public class OpenApiConfig {
}
